# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Will LaBranche 
tagline:          "Software Engineer"
description:      ''
url:              "http://www.labranche.io"
paginate:         5
paginate_path:    "blog/page:num"

baseurl:          ""

author:
  name:           "Will LaBranche"
  url:            "http://www.labranche.io"

github_repo:      "https://github.com/wlabranche/labranche.io"

networks:
  github:           "https://github.com/wlabranche/"
  twitter:          ""
  linkedin:         "http://www.linkedin.com/in/wlabranche"
  facebook:         ""
  codepen:          ""
